### ISSUE TITLE
Backbonejs 1.1 vs 1.2dev and svg namespace

### ISSUE THREAD

**Issue by SylvainCorlay** [akre54/Backbone.D3View#2]
Thanks for sharing this - I am glad you guys start offering the possibility to use other DOM manipulation programs than jQuery.

- For d3view, you set the default namespace to svg. On this regard, the corresponding string is available in d3 as `d3.ns.prefix.svg`. By the way, allowing to set the namespace could be interesting for any view and not just d3 views. (Besides, d3 can also be used for general DOM manipulation outside of svg... Maybe this could default to the general namespace rather than svg...)

- It seems that this requires the current dev version of backbonejs (1.2dev) and that it does not work with backbone 1.1. (In particular, overloading _setElement with version 1.1 has no effect.) Might be worth mentioning in the Readme.md.

**Comment by akre54** [comment]
>  the corresponding string is available in d3 as `d3.ns.prefix.svg`

Good tip, thanks!

> By the way, allowing to set the namespace could be interesting for any view and not just d3 views. 

It'd be great to see a patch if you have an idea for what an implementation would look like.

> Might be worth mentioning in the Readme.md.

Right. When I first wrote this (and NativeView) I didn't think it would take a year for the next version to come out. I'll add a note.
