### ISSUE TITLE
plans to publish on npm?

### ISSUE THREAD

**Issue by jameslaneconkling** [akre54/Backbone.D3View#3]
Would be quite useful, as in my experience, backbone and browserify make a great combo.

**Comment by akre54** [comment]
Ah yep. Oversight on my part. Published.

**Comment by jameslaneconkling** [comment]
Thanks so much.  Really excited about this plugin--kudos for the good work.

**Comment by tom-spalding** [comment]
`npm install --save backbone.d3view`
